ALTER TABLE PLANETS RENAME TO PLANETS_TEMP;
ALTER TABLE MOONS RENAME TO MOONS_TEMP;

CREATE TABLE PLANETS (_id INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT, DESCRIPTION TEXT, APHELION NUMERIC, PERIHELION NUMERIC, ORBITAL_PERIOD TEXT, RADIUS TEXT, DENSITY NUMERIC, GRAVITY NUMERIC, FAVORITE INTEGER, IMAGE TEXT);

CREATE TABLE MOONS (_id INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT, DESCRIPTION TEXT, APOGEE INTEGER, PERIGEE INTEGER, SATELLITE_OF TEXT, RADIUS TEXT, GRAVITY NUMERIC, FAVORITE INTEGER, IMAGE TEXT);

/*INSERT INTO PLANETS (_id, NAME, DESCRIPTION, APHELION, PERIHELION, ORBITAL_PERIOD, RADIUS, DENSITY, GRAVITY, FAVORITE, IMAGE) SELECT (_id, NAME, DESCRIPTION, APHELION, PERIHELION, ORBITAL_PERIOD, RADIUS, DENSITY, GRAVITY, FAVORITE, IMAGE) FROM PLANETS_TEMP;
INSERT INTO MOONS (_ID, NAME, DESCRIPTION, APOGEE, PERIGEE, SATELLITE_OF, RADIUS, GRAVITY, FAVORITE, IMAGE) SELECT (_id, NAME, DESCRIPTION, APOGEE, PERIGEE, SATELLITE_OF, RADIUS, GRAVITY, FAVORITE, IMAGE) FROM MOONS_TEMP;
*/

INSERT INTO PLANETS SELECT * FROM PLANETS_TEMP;
INSERT INTO MOONS SELECT * FROM MOONS_TEMP;

DROP TABLE PLANETS_TEMP;
DROP TABLE MOONS_TEMP;